spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
    default-locale: ko_KR

  datasource:
    url: jdbc:h2:mem:musinsa;DATABASE_TO_UPPER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_updates: true
    open-in-view: false

  sql:
    init:
      mode: always

  flyway:
    url: jdbc:h2:mem:musinsa;DATABASE_TO_UPPER=TRUE
    user: sa
    password:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    validateOnMigrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
